
list.Add( "OverrideMaterials", "jacobsrose/metal/aluminium/scaffed/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/metal/steel/streaked/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/metal/steel/used/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/fabric/twill/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/leather/018/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/leather/035d/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/leather/033b/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/leather/035b/pbr" )

list.Add( "OverrideMaterials", "jacobsrose/carbon/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/marble/013/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/plastic/013a/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/wood/051/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/fabric/060/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/fabric/030/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/fabric/014/pbr" )

list.Add( "OverrideMaterials", "jacobsrose/metal/021/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/metal/006/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/metal/010/pbr" )
list.Add( "OverrideMaterials", "jacobsrose/metal/044a/pbr" )